package com.sam.service;

import com.sam.dto.Employee;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;

public class EmployeeServiceTest {

    @InjectMocks
    EmployeeService employeeService;

    @BeforeEach
    public void setup() {
        //employeeService = new EmployeeService(); // this was generated by copilot
        MockitoAnnotations.openMocks(this);
    }

    // partial auto generated test case
    @Test
    public void testCalculateSalary() {
        Employee e = new Employee();
        e.setAge(40);

        EmployeeService employeeService = new EmployeeService();
        int salary = employeeService.calculateSalary(e);
        assertEquals(30000, salary);
    }

    //auto generated test case
    @Test
    public void testCalculateSalaryForSeniorCitizen() {
        Employee e = new Employee();
        e.setAge(60);

        EmployeeService employeeService = new EmployeeService();
        int salary = employeeService.calculateSalary(e);
        assertEquals(50000, salary);
    }

    //auto generated test case
    @Test
    public void testSeniorCitizen() {
        Employee e = new Employee();
        e.setAge(70);

        boolean isSeniorCitizen = employeeService.isSeniorCitizen(e);
        assertTrue(isSeniorCitizen); //assertEquals(true, isSeniorCitizen);  --> this was generated by copilot
    }

    //auto generated test case
    @Test
    public void testNotSeniorCitizen() {
        Employee e = new Employee();
        e.setAge(50);

        boolean isSeniorCitizen = employeeService.isSeniorCitizen(e);
        assertFalse(isSeniorCitizen); //assertTrue(!isSeniorCitizen);  --> this was generated by copilot
    }
}
